const languages = [
    { code: "ace_Arab", name: "Acehnese (Arabic script)" },
    { code: "ace_Latn", name: "Acehnese (Latin script)" },
    { code: "acm_Arab", name: "Mesopotamian Arabic" },
    { code: "acq_Arab", name: "Ta’izzi-Adeni Arabic" },
    { code: "aeb_Arab", name: "Tunisian Arabic" },
    { code: "afr_Latn", name: "Afrikaans" },
    { code: "ajp_Arab", name: "South Levantine Arabic" },
    { code: "aka_Latn", name: "Akan" },
    { code: "amh_Ethi", name: "Amharic" },
    { code: "apc_Arab", name: "North Levantine Arabic" },
    { code: "arb_Arab", name: "Modern Standard Arabic" },
    { code: "ars_Arab", name: "Najdi Arabic" },
    { code: "ary_Arab", name: "Moroccan Arabic" },
    { code: "arz_Arab", name: "Egyptian Arabic" },
    { code: "asm_Beng", name: "Assamese" },
    { code: "ast_Latn", name: "Asturian" },
    { code: "awa_Deva", name: "Awadhi" },
    { code: "ayr_Latn", name: "Aymara" },
    { code: "azb_Arab", name: "South Azerbaijani" },
    { code: "azj_Latn", name: "North Azerbaijani" },
    { code: "bak_Cyrl", name: "Bashkir" },
    { code: "bam_Latn", name: "Bambara" },
    { code: "ban_Latn", name: "Balinese" },
    { code: "bel_Cyrl", name: "Belarusian" },
    { code: "bem_Latn", name: "Bemba" },
    { code: "ben_Beng", name: "Bengali" },
    { code: "bho_Deva", name: "Bhojpuri" },
    { code: "bjn_Arab", name: "Banjar (Arabic script)" },
    { code: "bjn_Latn", name: "Banjar (Latin script)" },
    { code: "bod_Tibt", name: "Tibetan" },
    { code: "bos_Latn", name: "Bosnian" },
    { code: "bug_Latn", name: "Buginese" },
    { code: "bul_Cyrl", name: "Bulgarian" },
    { code: "cat_Latn", name: "Catalan" },
    { code: "ceb_Latn", name: "Cebuano" },
    { code: "ces_Latn", name: "Czech" },
    { code: "cjk_Latn", name: "Chokwe" },
    { code: "ckb_Arab", name: "Central Kurdish" },
    { code: "crh_Latn", name: "Crimean Tatar" },
    { code: "cym_Latn", name: "Welsh" },
    { code: "dan_Latn", name: "Danish" },
    { code: "deu_Latn", name: "German" },
    { code: "dik_Latn", name: "Dinka" },
    { code: "dyu_Latn", name: "Dyula" },
    { code: "dzo_Tibt", name: "Dzongkha" },
    { code: "ell_Grek", name: "Greek" },
    { code: "eng_Latn", name: "English" },
    { code: "epo_Latn", name: "Esperanto" },
    { code: "est_Latn", name: "Estonian" },
    { code: "eus_Latn", name: "Basque" },
    { code: "ewe_Latn", name: "Ewe" },
    { code: "fao_Latn", name: "Faroese" },
    { code: "fij_Latn", name: "Fijian" },
    { code: "fin_Latn", name: "Finnish" },
    { code: "fra_Latn", name: "French" },
    { code: "fuv_Latn", name: "Nigerian Fulfulde" },
    { code: "gla_Latn", name: "Scottish Gaelic" },
    { code: "gle_Latn", name: "Irish" },
    { code: "glg_Latn", name: "Galician" },
    { code: "grn_Latn", name: "Guarani" },
    { code: "guj_Gujr", name: "Gujarati" },
    { code: "hat_Latn", name: "Haitian Creole" },
    { code: "hau_Latn", name: "Hausa" },
    { code: "heb_Hebr", name: "Hebrew" },
    { code: "hin_Deva", name: "Hindi" },
    { code: "hrv_Latn", name: "Croatian" },
    { code: "hun_Latn", name: "Hungarian" },
    { code: "hye_Armn", name: "Armenian" },
    { code: "ibo_Latn", name: "Igbo" },
    { code: "ilo_Latn", name: "Ilocano" },
    { code: "ind_Latn", name: "Indonesian" },
    { code: "isl_Latn", name: "Icelandic" },
    { code: "ita_Latn", name: "Italian" },
    { code: "jav_Latn", name: "Javanese" },
    { code: "jpn_Jpan", name: "Japanese" },
    { code: "kan_Knda", name: "Kannada" },
    { code: "kas_Arab", name: "Kashmiri (Arabic script)" },
    { code: "kaz_Cyrl", name: "Kazakh" },
    { code: "khm_Khmr", name: "Khmer" },
    { code: "kor_Hang", name: "Korean" },
    { code: "lao_Laoo", name: "Lao" },
    { code: "lat_Latn", name: "Latin" },
    { code: "lit_Latn", name: "Lithuanian" },
    { code: "ltz_Latn", name: "Luxembourgish" },
    { code: "lug_Latn", name: "Ganda" },
    { code: "mal_Mlym", name: "Malayalam" },
    { code: "mar_Deva", name: "Marathi" },
    { code: "msa_Latn", name: "Malay" },
    { code: "mya_Mymr", name: "Burmese" },
    { code: "nld_Latn", name: "Dutch" },
    { code: "nor_Latn", name: "Norwegian" },
    { code: "pan_Guru", name: "Punjabi" },
    { code: "pol_Latn", name: "Polish" },
    { code: "por_Latn", name: "Portuguese" },
    { code: "ron_Latn", name: "Romanian" },
    { code: "rus_Cyrl", name: "Russian" },
    { code: "spa_Latn", name: "Spanish" },
    { code: "tam_Taml", name: "Tamil" },
    { code: "tel_Telu", name: "Telugu" },
    { code: "tha_Thai", name: "Thai" },
    { code: "tur_Latn", name: "Turkish" },
    { code: "urd_Arab", name: "Urdu" },
    { code: "vie_Latn", name: "Vietnamese" },
    { code: "zho_Hans", name: "Chinese (Simplified)" }
  ];
  
  export default languages;  